import dayjs from 'dayjs'
import globalConfig from '../../classes/globalConfig'
import tableToClass from '../tableToClass/tableToClass'
import testData from '../tableToClass/testData.json'
import { makeSchedule } from './makeSchedule'
describe('makeSchedule', ()=>{
    tableToClass(testData)
    globalConfig.holidays = [dayjs('2021-09-20'), dayjs('2021-09-23')]
    test('test makeSchedule', ()=>{
        const result = makeSchedule()
        expect(result[0].member.name).toBe('test')
        expect(result[0].date.format('YYYY/MM/DD')).toBe('2021/09/06')
        expect(result[1].member.name).toBe('夕暮おこは')
        expect(result[1].date.format('YYYY/MM/DD')).toBe('2021/09/08')
        expect(result[2].member.name).toBe('kmatsui058')
        expect(result[2].date.format('YYYY/MM/DD')).toBe('2021/09/09')
        expect(result[3].member.name).toBe('test')
        expect(result[3].date.format('YYYY/MM/DD')).toBe('2021/09/13')
        expect(result[4].member.name).toBe('kmatsui058')
        expect(result[4].date.format('YYYY/MM/DD')).toBe('2021/09/14')
        expect(result[5].member.name).toBe('夕暮おこは')
        expect(result[5].date.format('YYYY/MM/DD')).toBe('2021/09/15')
        expect(result[6].member.name).toBe('test')
        expect(result[6].date.format('YYYY/MM/DD')).toBe('2021/09/16')
        expect(result[7].member.name).toBe('kmatsui058')
        expect(result[7].date.format('YYYY/MM/DD')).toBe('2021/09/21')
        expect(result[8].member.name).toBe('夕暮おこは')
        expect(result[8].date.format('YYYY/MM/DD')).toBe('2021/09/22')
        expect(result[9].member.name).toBe('test')
        expect(result[9].date.format('YYYY/MM/DD')).toBe('2021/09/27')
        expect(result[10].member.name).toBe('kmatsui058')
        expect(result[10].date.format('YYYY/MM/DD')).toBe('2021/09/28')
        expect(result[11].member.name).toBe('夕暮おこは')
        expect(result[11].date.format('YYYY/MM/DD')).toBe('2021/09/29')
        expect(result[12].member.name).toBe('test')
        expect(result[12].date.format('YYYY/MM/DD')).toBe('2021/09/30')
        expect(result[13].member.name).toBe('kmatsui058')
        expect(result[13].date.format('YYYY/MM/DD')).toBe('2021/10/04')
        expect(result[14].member.name).toBe('test')
        expect(result[14].date.format('YYYY/MM/DD')).toBe('2021/10/05')
        expect(result[15].member.name).toBe('夕暮おこは')
        expect(result[15].date.format('YYYY/MM/DD')).toBe('2021/10/06')
        expect(result[16].member.name).toBe('kmatsui058')
        expect(result[16].date.format('YYYY/MM/DD')).toBe('2021/10/07')
        expect(result[17].member.name).toBe('夕暮おこは')
        expect(result[17].date.format('YYYY/MM/DD')).toBe('2021/10/11')
    })
})
